version: '3'

services:
    app:
        build:
            context: .  # Путь до корневой директории проекта
            dockerfile: ./docker/php-fpm/Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        tty: true
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - db
        command: sh -c "php artisan migrate --seed && php artisan serve --host=0.0.0.0 --port=8000"
        networks:
            - net

    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        depends_on:
            - db
        volumes:
            - ./:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - net

    db:
        image: mysql
        container_name: db
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "${DB_PORT}:3306"
        networks:
            - net

networks:
    net:
        driver: bridge
volumes:
    dbdata:
